### ISSUE TITLE
Question about the mirror

### ISSUE THREAD

**Issue by brock** [yahoo/reginabox#2]
Hey guys, really interesting project here.

One thing I wasn't able to figure out when looking through mirror.js was how this actually fetches all the items in the npm registry. I was kind of surprised that it was even doing this, to be honest. I've tried out npm_lazy before, and didn't realize this was going to _actually create a mirror_. :)

**Comment by davglass** [comment]
I uses my [`registry-static`](https://www.npmjs.com/package/registry-static) module under the hood. That module follows the CouchDB feed from the registry, then mirrors the contents of the modules to the HDD so that you get a read-only mirror. We use this internally to host our own mirrors.
